# -*- coding: utf-8 -*-
"""과제3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120dYxZAUFdTa0CtlYAQXacDPJhSKqd6l
"""

def gcd(a, b): #최대공약수 구하기(유클리드호제법사용)
  if (a < b): #a가 더 큰 수가 되도록
    tmp = a
    a = b
    b = tmp
  if (b == 0):
    return a
  return gcd(b, a%b) #재귀함수 사용하여 계속 나누도록

def lcm(a, b): #최소공배수 구하기
  tmp = int(gcd(a, b)) #최대공약수 구해오기
  a_tmp = a / tmp
  b_tmp = b / tmp
  a = int(tmp * a_tmp * b_tmp) 
  return a

a = int(input("첫번째 숫자를 입력하세요: ")) #숫자 입력
b = int(input("두번째 숫자를 입력하세요: "))

print("최대공약수는 "+str(gcd(a, b))) #결과 출력
print("최소공배수는 "+str(lcm(a, b)))