# -*- coding: utf-8 -*-
"""과제1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JCso9zZYu1LffBG-JbrxA-Ezo6XbAwYK
"""

def check(ttt, mark): #이긴 사람이나 컴퓨터가 있는지 확인
  for i in range(0, 3): #하나의 행을 만족했는지
    if ttt[i][0]+ttt[i][1]+ttt[i][2] == mark*3:
      return 1
  for i in range (0, 3): #하나의 열을 만족했는지
    if ttt[0][i]+ttt[1][i]+ttt[2][i] == mark*3:
      return 1
  if ttt[0][0]+ttt[1][1]+ttt[2][2] == mark*3: #대각선을 만족했는지
    return 1
  if ttt[0][2]+ttt[1][1]+ttt[2][0] == mark*3: #대각선을 만족했는지
    return 1
  return 0

def man_do(ttt, mark):
  print("")
  man_col = input("행을 입력하세요: ") #행과 열 입력받음
  man_row = input("열을 입력하세요: ")
  print("("+man_col+","+man_row+") 선택")
  man_col = int(man_col) - 1
  man_row = int(man_row) - 1
  if (ttt[man_col][man_row] != " "): #중복 체크
    print("잘못된 선택입니다.") #중복이면 다시
    man_do(ttt, mark)
  ttt[man_col][man_row] = mark #중복 아니면 표시

  print("사람이 선택했습니다.")
  for i in range(0, 3):
	  print(ttt[i])

  return ttt

def com_do(ttt, mark):
  while (1):
    com_col = random.randrange(0, 3) #랜덤으로 행과 열 선택
    com_row = random.randrange(0, 3)
  
    if (ttt[com_col][com_row] == " "): #중복 체크

      ttt[com_col][com_row] = mark #중복 아니면 표시

      print("컴퓨터가 선택했습니다.")
      for i in range(0, 3):
	      print(ttt[i])
   
      return ttt

def man_first(ttt):
  print("")

  while (1):
    man_do(ttt, "X") #사람이 먼저니까 X 선택
    #각 순서가 끝난 후 승리여부 확인
    man_win = check(ttt, "X")
    com_win = check(ttt, "O")
    
    if (man_win == 1):
      print("사람의 승리!")
      break
    if (com_win == 1):
      print("컴퓨터의 승리!")
      break

    com_do(ttt, "O") #컴퓨터가 나중이니까 O 선택
    #각 순서가 끝난 후 승리여부 확인
    man_win = check(ttt, "X")
    com_win = check(ttt, "O")
    

    if (man_win == 1):
      print("사람의 승리!")
      break
    if (com_win == 1):
      print("컴퓨터의 승리!")
      break

def com_first(ttt):
  print("")

  while (1):
    com_do(ttt, "X") #컴퓨터가 먼저니까 X 선택
    #각 순서가 끝난 후 승리여부 확인
    man_win = check(ttt, "O") 
    com_win = check(ttt, "X")
    
    if (man_win == 1):
      print("사람의 승리!")
      break
    if (com_win == 1):
      print("컴퓨터의 승리!")
      break

    man_do(ttt, "O") #사람이 나중이니까 O 선택
    #각 순서가 끝난 후 승리여부 확인
    man_win = check(ttt, "O")
    com_win = check(ttt, "X")
  
    if (man_win == 1):
      print("사람의 승리!")
      break
    if (com_win == 1):
      print("컴퓨터의 승리!")
      break

import random

ttt = [[" ", " ", " "], [" ", " ", " "], [" ", " ", " "]]
ending = 0
print("start!") #시작
for i in range(0, 3):
	print(ttt[i])



starting = random.randrange(0, 2) #랜덤으로 누가 시작할지 결정
if (starting == 0):
  print("사람이 먼저 시작합니다. \n")
  man_first(ttt) #사람먼저함수실행
else:
  print("컴퓨터가 먼저 시작합니다. \n")
  com_first(ttt) #컴퓨터먼저함수실행